In [1]:
from regression_datasets import provide_data
import numpy as np
import torch

In [11]:
meta_train_data, meta_valid_data, meta_test_data = provide_data(dataset='berkeley', data_dir="./filelists/sensor_data/")

print("type meta_train_data :",type(meta_train_data))
print("len meta_train_data :", len(meta_train_data))
print("all meta_train_data[i] are of len 2 :", all([len(meta_train_task)==2 for meta_train_task in meta_train_data]))

print(meta_train_data[0][0].shape)
print(meta_train_data[0][1].shape)
print(meta_train_data[35][0].shape)
print(meta_train_data[35][1].shape)

print()

print("type meta_valid_data :",type(meta_valid_data))
print("len meta_valid_data :", len(meta_valid_data))
print("all meta_valid_data[i] are of len 2 :", all([len(meta_valid_task)==4 for meta_valid_task in meta_valid_data]))

print(meta_valid_data[0][0].shape)
print(meta_valid_data[0][1].shape)
print(meta_valid_data[0][2].shape)
print(meta_valid_data[0][3].shape)
print(meta_valid_data[9][0].shape)
print(meta_valid_data[9][1].shape)
print(meta_valid_data[9][2].shape)
print(meta_valid_data[9][3].shape)

print()

print("type meta_test_data :",type(meta_test_data))
print("len meta_test_data :", len(meta_test_data))
print("all meta_test_data[i] are of len 2 :", all([len(meta_test_task)==4 for meta_test_task in meta_test_data]))

print(meta_test_data[0][0].shape)
print(meta_test_data[0][1].shape)
print(meta_test_data[9][0].shape)
print(meta_test_data[9][1].shape)

print()

print("Meta valid data == meta test data :", meta_valid_data == meta_test_data)

print()
print(meta_train_data[0][0][0])
print(meta_test_data[0][0][0])

type meta_train_data : <class 'list'>
len meta_train_data : 36
all meta_train_data[i] are of len 2 : True
(30, 11)
(30,)
(30, 11)
(30,)

type meta_valid_data : <class 'list'>
len meta_valid_data : 10
all meta_valid_data[i] are of len 2 : True
(30, 11)
(30,)
(288, 11)
(288,)
(30, 11)
(30,)
(288, 11)
(288,)

type meta_test_data : <class 'list'>
len meta_test_data : 10
all meta_test_data[i] are of len 2 : True
(30, 11)
(30,)
(30, 11)
(30,)

Meta valid data == meta test data : True

[18.39978621 18.391      18.38453846 18.37771556 18.39078222 18.3616
 18.36125    18.32620395 18.33007237 18.33394079  0.19430951]
[24.17601539 24.1436     24.13768889 24.11574737 24.1044     24.0848
 24.0799     24.0456     24.0456     24.03315555  0.79736294]


In [3]:
def convert_big_tuple(meta_data):
    arrX_list = []
    arrY_list = []
    for (arrX, arrY) in meta_data:
        arrX_list.append(arrX)  # (30, 11)
        arrY_list.append(arrY)  # (30,)

    big_X_np = np.stack(arrX_list, axis=0)
    big_Y_np = np.stack(arrY_list, axis=0)

    big_X_torch = torch.from_numpy(big_X_np)
    big_Y_torch = torch.from_numpy(big_Y_np)

    return big_X_torch, big_Y_torch

meta_X, meta_label = convert_big_tuple(meta_train_data)
print(meta_X.shape, meta_label.shape)

torch.Size([36, 30, 11]) torch.Size([36, 30])


In [3]:
meta_train_data, meta_valid_data, meta_test_data = provide_data(dataset='argus', data_dir="./filelists/argus_data/")

print("type meta_train_data :",type(meta_train_data))
print("len meta_train_data :", len(meta_train_data))
print("all meta_train_data[i] are of len 2 :", all([len(meta_train_task) for meta_train_task in meta_train_data]))

print(meta_train_data[0][0].shape)
print(meta_train_data[0][1].shape)
print(meta_train_data[19][0].shape)
print(meta_train_data[19][1].shape)

print(meta_train_data[0][0])

type meta_train_data : <class 'list'>
len meta_train_data : 20
all meta_train_data[i] are of len 2 : True
(100, 3)
(100,)
(100, 3)
(100,)
[[ 309.22539054  806.20020002 1172.06124213]
 [ 146.90482478 1173.28170533  804.89948797]
 [ 170.49502954 1064.39652642 3027.97672009]
 [ 157.19579372  791.05184074 3957.13067775]
 [ 219.61237874  431.42307034 3538.27540477]
 [ 139.89358659 1082.12505488 1261.48208412]
 [ 232.98378799  804.13557021 2100.81856169]
 [ 220.44212391  911.76094543 3993.81737052]
 [ 353.69481922  548.18741687 3656.17165388]
 [ 330.58989517  320.49436637 3063.54633095]
 [ 308.87396107  435.48491541 1593.21656475]
 [ 111.60396018  773.6284929  1071.85408101]
 [ 219.9265377   963.77349659 3124.60056546]
 [ 125.15435341  514.7563068   913.88421027]
 [ 132.84132179 1134.97694629 1794.28608941]
 [ 304.74343359  558.53111943  559.63011453]
 [ 319.23129672 1165.78238293 3526.69482765]
 [ 186.61484558  817.78155749 2552.35822302]
 [ 386.72199596  357.11421505 2851.81271079]
 [ 109.

In [13]:
meta_train_data, meta_valid_data, meta_test_data = provide_data(dataset='swissfel', data_dir="./filelists/sensor_data/")

print("type meta_train_data :",type(meta_train_data))
print("len meta_train_data :", len(meta_train_data))
print("all meta_train_data[i] are of len 2 :", all([len(meta_train_task) for meta_train_task in meta_train_data]))

print(meta_train_data[0][0].shape)
print(meta_train_data[0][1].shape)
print(meta_train_data[35][0].shape)
print(meta_train_data[35][1].shape)

print(meta_train_data[0][0])

swissfel_dir


FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './filelists/sensor_data/2018_10_31/neldermead/data/evaluations.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)